export const sampleData = [
  {
    encounterID: '1',
    callDateTime: '2024-01-29 21:24:58',
    callerIsPatient: false,
    caller: {
      callerName: 'Joe blogs',
      callerRelationship: 'wife',
      callerContactNo: '0839000538',
      isCallBackNumber: true,
    },
    patient: {
      patientID: '1',
      dob: '1979-01-01',
      dobUnKnown: true,
      age: '',
      isApproxAge: false,
      firstName: 'John',
      lastName: 'Doe',
      gender: 'male',
      callBackNumber: '0839000538',
      ppsN: null,
      email: null,
      homeLocation: {
        homeOrBuilding: '9 Dalriada Walk',
        street: 'Dalriada Avenue',
        areaOrTown: 'Knocklyon',
        cityOrCounty: 'Dublin 16',
        eirCode: 'D16 CC01',
        isSetToCurrentLocation: true,
        isBillingAddress: true,
      },
      currentLocation: {
        homeOrBuilding: null,
        street: null,
        areaOrTown: null,
        cityOrCounty: null,
        eirCode: null,
        isSetToCurrentLocation: false,
        isBillingAddress: true,
        expiryDatetime: null,
      },
      homeContact: { contact: null, isCallBackNumber: null },
      mobileContact: { contact: null, isCallBackNumber: null },
      otherContact: { contact: null, isCallBackNumber: null },
      medicalCover: { coverType: null, cardNumber: null, expiryDate: null },
      gpDetails: { registrationStatus: null, gp: null, surgery: null },
      presentingComplaints: [
        { complaint: 'cough' },
        { complaint: 'sore throat' },
        { complaint: 'temprature' },
      ],
      additionalNotes: null,
      priority: null,
      priorityComments: null,
    },
  },
  {
    encounterID: '2',
    callDateTime: '2024-01-29 21:24:58',
    callerIsPatient: true,
    caller: {
      callerName: '',
      callerRelationship: '',
      callerContactNo: '',
      isCallBackNumber: false,
    },
    patient: {
      patientID: '2',
      dob: '1986-01-01',
      dobUnKnown: false,
      age: '',
      isApproxAge: false,
      firstName: 'Joe',
      lastName: 'Blogs',
      gender: 'female',
      callBackNumber: '0839000538',
      ppsN: null,
      email: null,
      homeLocation: {
        homeOrBuilding: null,
        street: null,
        areaOrTown: null,
        cityOrCounty: null,
        eirCode: null,
        isSetToCurrentLocation: true,
        isBillingAddress: true,
      },
      currentLocation: {
        homeOrBuilding: null,
        street: null,
        areaOrTown: null,
        cityOrCounty: null,
        eirCode: null,
        isSetToCurrentLocation: false,
        isBillingAddress: true,
        expiryDatetime: null,
      },
      homeContact: { contact: null, isCallBackNumber: null },
      mobileContact: { contact: null, isCallBackNumber: null },
      otherContact: { contact: null, isCallBackNumber: null },
      medicalCover: { coverType: null, cardNumber: null, expiryDate: null },
      gpDetails: { registrationStatus: null, gp: null, surgery: null },
      presentingComplaints: [
        { complaint: 'cough' },
        { complaint: 'sore throat' },
        { complaint: 'temprature' },
      ],
      additionalNotes: null,
      priority: null,
      priorityComments: null,
    },
  },
  {
    encounterID: '3',
    callDateTime: '2024-01-29 21:24:58',
    callerIsPatient: false,
    caller: {
      callerName: 'Joe blogs',
      callerRelationship: 'wife',
      callerContactNo: '0839000538',
      isCallBackNumber: true,
    },
    patient: {
      patientID: '3',
      dob: '2005-01-01',
      dobUnKnown: false,
      age: '',
      isApproxAge: false,
      firstName: 'Jane',
      lastName: 'Doe',
      gender: 'female',
      callBackNumber: '0839000538',
      ppsN: null,
      email: null,
      homeLocation: {
        homeOrBuilding: null,
        street: null,
        areaOrTown: null,
        cityOrCounty: null,
        eirCode: null,
        isSetToCurrentLocation: true,
        isBillingAddress: true,
      },
      currentLocation: {
        homeOrBuilding: null,
        street: null,
        areaOrTown: null,
        cityOrCounty: null,
        eirCode: null,
        isSetToCurrentLocation: false,
        isBillingAddress: true,
        expiryDatetime: null,
      },
      homeContact: { contact: null, isCallBackNumber: null },
      mobileContact: { contact: null, isCallBackNumber: null },
      otherContact: { contact: null, isCallBackNumber: null },
      medicalCover: { coverType: null, cardNumber: null, expiryDate: null },
      gpDetails: { registrationStatus: null, gp: null, surgery: null },
      presentingComplaints: [
        { complaint: 'cough' },
        { complaint: 'sore throat' },
        { complaint: 'temprature' },
      ],
      additionalNotes: null,
      priority: null,
      priorityComments: null,
    },
  },
  // {
  //   encounterID: '4',
  //   callDateTime: '2024-01-29 21:33:01',
  //   callerIsPatient: true,
  //   caller: {
  //     callerName: null,
  //     callerRelationship: {},
  //     callerContactNo: null,
  //     isCallBackNumber: null,
  //   },
  //   patient: {
  //     patientID: '4',
  //     dob: '2001-01-01',
  //     dobUnKnown: false,
  //     age: '',
  //     isApproxAge: false,
  //     firstName: 'Angalina',
  //     lastName: 'Juli',
  //     gender: 'female',
  //     callBackNumber: '0855003908',
  //     ppsN: null,
  //     email: null,
  //     homeLocation: {
  //       homeOrBuilding: null,
  //       street: null,
  //       areaOrTown: null,
  //       cityOrCounty: null,
  //       eirCode: null,
  //       isSetToCurrentLocation: false,
  //       isBillingAddress: false,
  //     },
  //     currentLocation: {
  //       homeOrBuilding: null,
  //       street: null,
  //       areaOrTown: null,
  //       cityOrCounty: null,
  //       eirCode: null,
  //       isSetToCurrentLocation: false,
  //       isBillingAddress: true,
  //       expiryDatetime: null,
  //     },
  //     homeContact: { contact: null, isCallBackNumber: null },
  //     mobileContact: { contact: null, isCallBackNumber: null },
  //     otherContact: { contact: null, isCallBackNumber: null },
  //     medicalCover: { coverType: null, cardNumber: null, expiryDate: null },
  //     gpDetails: { registrationStatus: null, gp: null, surgery: null },
  //     presentingComplaints: [
  //       { complaint: 'cough' },
  //       { complaint: 'sore throat' },
  //       { complaint: 'temprature' },
  //     ],
  //     additionalNotes: null,
  //     priority: null,
  //     priorityComments: null,
  //   },
  // },
  // {
  //   encounterID: '5',
  //   callDateTime: '2024-01-29 21:36:30',
  //   callerIsPatient: true,
  //   caller: {
  //     callerName: null,
  //     callerRelationship: {},
  //     callerContactNo: null,
  //     isCallBackNumber: null,
  //   },
  //   patient: {
  //     patientID: '5',
  //     dob: null,
  //     dobUnKnown: true,
  //     age: '30',
  //     isApproxAge: 'yes',
  //     firstName: 'Tom',
  //     lastName: 'Cruse',
  //     gender: 'male',
  //     callBackNumber: '0839538000',
  //     ppsN: null,
  //     email: 'tomcruse@test.com',
  //     homeLocation: {
  //       homeOrBuilding: null,
  //       street: null,
  //       areaOrTown: null,
  //       cityOrCounty: null,
  //       eirCode: null,
  //       isSetToCurrentLocation: true,
  //       isBillingAddress: true,
  //     },
  //     currentLocation: {
  //       homeOrBuilding: null,
  //       street: null,
  //       areaOrTown: null,
  //       cityOrCounty: null,
  //       eirCode: null,
  //       isSetToCurrentLocation: false,
  //       isBillingAddress: true,
  //       expiryDatetime: null,
  //     },
  //     homeContact: { contact: null, isCallBackNumber: null },
  //     mobileContact: { contact: null, isCallBackNumber: null },
  //     otherContact: { contact: null, isCallBackNumber: null },
  //     medicalCover: { coverType: null, cardNumber: null, expiryDate: null },
  //     gpDetails: { registrationStatus: null, gp: null, surgery: null },
  //     presentingComplaints: [{ complaint: 'cough' }],
  //     additionalNotes: null,
  //     priority: 'routine',
  //     priorityComments: null,
  //   },
  // },
];
